services:
  neo4j:
    image: neo4j:latest
    container_name: neo4j-playground
    environment:
      NEO4J_AUTH: neo4j/demo_secret  # Ensure the password is at least 8 characters
    volumes:
      - ./data:/data
      - ./logs:/logs
      - ./import:/var/lib/neo4j/import
      - ./plugins:/plugins
    ports:
      - "7474:7474"
      - "7687:7687"
